com:
  bot:
    calculation:
      settings:
        TOKEN: ${TOKEN}
        NAME: ${NAME}
      job:
        crypto:
          executors:
            pool-size: 1
            enabled: true
            cron: '0 0/5 * * * *' #расписание выполнения обработчика (каждые 5 мин)
#            cron: '* * * * * *' #расписание выполнения обработчика (каждую сек)
        fiat:
          executors:
            pool-size: 1
            enabled: true
            cron: '0 0 7 * * *' #расписание выполнения обработчика (в 7 утра)

spring:
  datasource:
    driver: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    platform: postgres
    initialization-mode: always
    jackson:
      serialization:
        write-dates-as-timestamps: true

  jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
#        temp:
#          use_jdbc_metadata_defaults: false
#        jdbc:
#          lob:
#            non_contextual_creation: true
server:
  port: ${PORT:9080}